/**
 * The site plays ONE Spotify playlist. Change it and everything follows: the
 * songs, and the "Spotify" link in the top bar.
 *
 * Easiest way to change it:
 *     npm run set:playlist <playlist url, uri, or id>
 *
 * How the tracks are resolved, in order:
 *
 *  1. `GET /v1/playlists/{id}/items` — the real source of truth. Note `items`,
 *     not `tracks` (that one is retired), and each entry wraps its track under
 *     an `item` key. This needs a CONNECTED visitor: an app token gets
 *     401 "Valid user authentication required", even for a public playlist.
 *  2. `SEED_TRACKS` below — what anonymous visitors see, since step 1 is not
 *     available to them. `set:playlist` regenerates it from the real playlist
 *     when you have a session, so the two stay in step.
 */

/** Accepts a full URL, a spotify: URI, or a bare id. */
export function parsePlaylistId(input: string): string {
  const trimmed = input.trim();
  // https://open.spotify.com/playlist/<id>?si=...
  const url = trimmed.match(/playlist\/([A-Za-z0-9]+)/);
  if (url) return url[1];
  // spotify:playlist:<id>
  const uri = trimmed.match(/spotify:playlist:([A-Za-z0-9]+)/);
  if (uri) return uri[1];
  return trimmed;
}

export const SPOTIFY_PLAYLIST_ID = parsePlaylistId(
  process.env.NEXT_PUBLIC_SPOTIFY_PLAYLIST_ID ?? "7xhJFVjjgA0jooeTrzevaN",
);

export const SPOTIFY_PLAYLIST_URL = `https://open.spotify.com/playlist/${SPOTIFY_PLAYLIST_ID}`;

export type SeedEntry = {
  spotifyId: string;
  /** Lookup term for the iTunes fallback, which supplies the audible preview. */
  search: string;
};

/**
 * GENERATED by `npm run set:playlist` — mirrors the playlist above.
 * Only consulted when the visitor has not connected Spotify.
 */
export const SEED_TRACKS: SeedEntry[] = [
  { spotifyId: "0Dt5EqEckM8jcfMYEdlx2Z", search: "Amsham Aksomaniac" },
  { spotifyId: "4XTgFBxBHN6var1BzAgE1m", search: "Jhol Maanu Annural Khalid" },
  { spotifyId: "1rDQJd8kzwBRXeoTtojkQn", search: "Roz Ritviz Nucleya" },
  { spotifyId: "6nRGPf5tpeJtKpXZO5cgIT", search: "Paro Aditya Rikhari" },
  { spotifyId: "3FjK86616FbluOfTxNK2gY", search: "ANXIETY Sleepy Hallow Doechii" },
];
